set(0,...
'defaultfigureposition',[380 320 540 200],...
'defaultaxeslinewidth',1.4,...
'defaultaxesfontsize',12,...
'defaultlinelinewidth',1.4,...
'defaultpatchlinewidth',1.4,...
'defaultlinemarkersize',18)
rand('state',sum(100*clock))
randn('state',2)
format compact, format long
splitting on
setpref('chebfun_defaults','maxn',128)
setpref('chebfun_defaults','degree_mode',1)
